In [74]:
import numpy as np

In [75]:
## Distributive property

# create random vectors
n = 10
a = np.random.randn(n)
b = np.random.randn(n)
c = np.random.randn(n)

# the two results
res1 = np.dot(a, (b + c))
res2 = np.dot(a, b) + np.dot(a, c)

# compare them
print([res1, res2])

[np.float64(-2.2755902196664937), np.float64(-2.275590219666493)]


In [76]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
print([np.dot(a, b + c), np.dot(a, b) + np.dot(a, c)])

[np.int64(82), np.int64(82)]


In [77]:
## Associative property

# create random vectors
n = 5
a = np.random.randn(n)
b = np.random.randn(n)
c = np.random.randn(n)


def test_associative(a, b, c):
    # the two results
    res1 = np.dot(a, np.dot(b, c))
    res2 = np.dot(np.dot(a, b), c)

    # compare them
    print(res1)
    print(res2)


test_associative(a, b, c)

[-0.40647202  0.01618875 -0.58978344  0.20003952 -0.19244731]
[ 0.18406914 -2.61382035 -1.88021138 -1.47510228 -0.18339069]


In [78]:
### special cases where associative property works!
# 1) one vector is the zeros vector
# 2) a==b==c

a = np.zeros(n)
test_associative(a, b, c)


[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [79]:
a = b = c = np.array([2, 3, 4])
test_associative(a, b, c)

[ 58  87 116]
[ 58  87 116]
