In [17]:
import numpy as np

In [18]:
A = np.random.randn(4, 6)
B = np.random.randn(4, 6)

In [19]:
A

array([[ 0.47335016, -1.83176954,  0.68390558, -0.79960282,  0.58654615,
        -0.82410661],
       [ 0.29462256,  0.14862224,  0.56585359,  0.24271031,  0.87502172,
         2.17227862],
       [ 0.46626712,  1.55037021, -0.94656326,  0.23548424, -0.3400851 ,
         0.7651856 ],
       [-0.36664894, -1.47505902, -0.31070796,  1.04226853, -0.90041027,
        -1.11869822]])

In [20]:
A[:, 0]

array([ 0.47335016,  0.29462256,  0.46626712, -0.36664894])

In [21]:
np.dot(A[:, 0], B[:, 0])

np.float64(0.1335580667660608)

In [22]:
sum(
    [
        A[0][0] * B[0][0],
        A[1][0] * B[1][0],
        A[2][0] * B[2][0],
        A[3][0] * B[3][0],
    ]
)

np.float64(0.13355806676606075)

In [23]:
dps = np.zeros(6)
for i in range(6):
    dps[i] = np.dot(A[:, i], B[:, i])
dps

array([ 0.13355807, -0.64375963, -3.57999298, -0.76942203,  2.18292899,
        0.25957051])